# Generated by Django 3.0.6 on 2020-05-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=255)),
                ("data", models.TextField(default=None, null=True)),
            ],
            options={"base_manager_name": "objects",},
        ),
    ]
