name: Verify backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        python setup.py install prod
    - name: Verify code formating
      run: |
        cd backend
        python setup.py verify_format
    - name: Test with pytest
      run: |
        cd backend
        pytest
